---
  - [Abdul, Abul]
  - [Alexander, Alex]
  - [Anandagopal, Ananda]
  - [Andrew, Andy]
  - [Anne, Ann]
  - [Anthony, Tony]
  - [Benjamin, Ben]
  - [Catherine, Cathy, Cath, Cate, Katherine, Kathy, Kath, Kate]
  - [Charlie, Charles]
  - [Chris, Christopher]
  - [Daniel, Danial, Danny, Dan]
  - [David, Dave]
  - [Deborah, Debbie]
  - [Des, Desmond]
  - [Douglas, Dougie]
  - [Eamonn, Eamon]
  - [Edward, Eddie, Eddy, Ed, Ned]
  - [Eric, Erick, Erik]
  - [Frederick, Frederic, Fred]
  - [Gerald, Gerry]
  - [Gerhard, Gerard, Ger, Gerry]
  - [James, Jim, Jimmy, Jamie]
  - [Joanna, Joan, Joanne]
  - [Joe, Joseph]
  - [John, Johnny]
  - [Jonathan, Jon]
  - [Lyubomir, Lubomir]
  - [Kenneth, Ken, Kenny]
  - [Michael, Mike, Mick, Micky, Mickie, Mikey, Micheal]
  - [Muthu, Muthukumaran]
  - [Nicholas, Nick, Nicolas]
  - [Nicola, Nickie, Nicky]
  - [Patrick, Pat, Paddy, Padraig, Padraic, Padhraig, Padhraic]
  - [Patricia, Paddy, Patty, Pat]
  - [Peter, Pete]
  - [Philip, Phillip, Phil]
  - [Philippe, Phillippe, Phil]
  - [Raymond, Ray]
  - [Rick, Ricky]
  - [Robert, Bob, Bobby]
  - [Rodney, Rod]
  - [Samual, Sam, Samuel]
  - [Stef, Stefan, Stephan, Stefen, Stephen]
  - [Steffy, Stefanie, Stephanie, Stefenie, Stephenie]
  - [Stephen, Steve, Steven]
  - [Terence, Terry]
  - [Thomas, Tom, Tommy]
  - [William, Will, Willy, Willie, Bill]
  - [Sean, John, !ruby/regexp /^Bradley$/]
