---
  - [Alexander, Alex]
  - [Andrew, Andy]
  - [Anthony, Tony]
  - [Benjamin, Ben]
  - [Catherine, Cathy, Cath]
  - [Daniel, Danny, Dan]
  - [David, Dave]
  - [Deborah, Debbie]
  - [Des, Desmond]
  - [Edward, Eddie, Eddy, Ed]
  - [Frederick, Fred]
  - [Frederic, Fred]
  - [Gerald, Gerry]
  - [Gerard, Gerry]
  - [James, Jim, Jimmy]
  - [John, Johnny]
  - [Jonathan, Jon]
  - [Kenneth, Ken, Kenny]
  - [Michael, Mike, Mick, Mikey]
  - [Nic, Nick, Nicolas]
  - [Nicola, Nickie, Nicky]
  - [Patrick, Pat]
  - [Patricia, Patty, Pat]
  - [Peter, Pete]
  - [Philip, Phil]
  - [Phillip, Phil]
  - [Rick, Ricky]
  - [Robert, Bob, Bobby]
  - [Samual, Sam]
  - [Samuel, Sam]
  - [Stephen, Steve]
  - [Steven, Steve]
  - [Terence, Terry]
  - [Thomas, Tom, Tommy]
  - [William, Will, Willy, Willie, Bill]
