---
  - [Deborah, Debbie]
  - [Demeter, Ceres]
  - [John, Johnny]
  - [Lyubomir, Lubomir]
  - [Michael, Mike]
  - [Patrick, Pat, Paddy, Padraig, Padraic, Padhraig, Padhraic]
  - [Philippe, Philip, Phillippe, Phillip]
  - [Stephen, Steve, Steven]
  - [William, Will, Willy, Willie, Bill]
  - [Sean, John, !ruby/regexp /^Bradley$/]
